In [2]:
import numpy as np



In [4]:
random = np.random.rand(10, 10)

rand_min = np.min(random)
rand_max = np.max(random)
print(rand_min)
print(rand_max)

0.004693021292368704
0.9957823140194623


In [5]:
a = np.ones((6,6))
a[1:-1, 1:-1] = 0
print(a)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
